fix: building in gatsby v7
Fix for this error...

Error: Interface field WpConnectionType.nodes expected but WpEnqueuedScriptConnectionType does not provide it.

Temporarily using gatsby-source-wordpress@7.8.0-alpha-wp-inconsistent-schema.29 because of
https://github.com/gatsbyjs/gatsby/issues/37729#issuecomment-1471124277"